name: firebase_ui
description: Firebase auth UI, dart package to mimic the firebaseUI(Google,Facebook,Twitter,Email supported)
version: 1.0.8
author: Nicholas Bowler <crucifixx25@gmail.com>
homepage: https://github.com/Maliffic/firebase_ui

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_twitter_login: 
    git:
      url: https://github.com/rsixel/flutter_twitter_login.git

  firebase_auth: ^0.21.0-1.1.nullsafety.1 

  google_sign_in: ^5.0.0-nullsafety
  flutter_facebook_login: ^3.0.0

  apple_sign_in: 
    git:
      url: https://github.com/rsixel/flutter_apple_sign_in.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fb-logo.png
    - assets/2.0x/fb-logo.png
    - assets/3.0x/fb-logo.png

    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/twitter-logo.png
    - assets/2.0x/twitter-logo.png
    - assets/3.0x/twitter-logo.png
